#!/usr/bin/env zsh

# mxfng.prompt | Prompt configuration for Zsh. Reference: https://github.com/spaceship-prompt/spaceship-prompt/blob/master/docs/options.md

# Order
SPACESHIP_PROMPT_ORDER=(
    time           # Time stamps section
    exec_time      # Execution time
    line_sep       # Line break
    user           # Username section
    dir            # Current directory section
    host           # Hostname section
    git            # Git section (git_branch + git_status)
    hg             # Mercurial section (hg_branch  + hg_status)
    package        # Package version
    node           # Node.js section
    bun            # Bun section
    deno           # Deno section
    ruby           # Ruby section
    python         # Python section
    elm            # Elm section
    elixir         # Elixir section
    xcode          # Xcode section
    swift          # Swift section
    golang         # Go section
    perl           # Perl section
    php            # PHP section
    rust           # Rust section
    haskell        # Haskell Stack section
    scala          # Scala section
    kotlin         # Kotlin section
    java           # Java section
    lua            # Lua section
    dart           # Dart section
    julia          # Julia section
    crystal        # Crystal section
    docker         # Docker section
    docker_compose # Docker section
    #aws            # Amazon Web Services section
    #gcloud         # Google Cloud Platform section
    #azure          # Azure section
    venv           # virtualenv section
    conda          # conda virtualenv section
    dotnet         # .NET section
    ocaml          # OCaml section
    vlang          # V section
    zig            # Zig section
    purescript     # PureScript section
    erlang         # Erlang section
    kubectl        # Kubectl context section
    ansible        # Ansible section
    terraform      # Terraform workspace section
    pulumi         # Pulumi stack section
    ibmcloud       # IBM Cloud section
    nix_shell      # Nix shell
    gnu_screen     # GNU Screen section
    async          # Async jobs indicator
    line_sep       # Line break
    battery        # Battery level and status
    jobs           # Background jobs indicator
    exit_code      # Exit code section
    sudo           # Sudo indicator
    char           # Prompt character
)

# Configuration
SPACESHIP_USER_SHOW=false
SPACESHIP_TIME_SHOW=true
SPACESHIP_EXEC_TIME_SHOW=true

# Symbols
SPACESHIP_CHAR_SYMBOL="馮】"  # Prompt

# Prefixes/Suffixes
SPACESHIP_PROMPT_PREFIXES_SHOW=false

# Colours
# Chart: https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
SPACESHIP_CHAR_COLOR_SUCCESS=117
SPACESHIP_DIR_COLOR=117
SPACESHIP_TIME_COLOR=117
SPACESHIP_GIT_BRANCH_COLOR=244
SPACESHIP_GIT_STATUS_COLOR=244
SPACESHIP_EXEC_TIME_COLOR=117

source $(brew --prefix)/opt/spaceship/spaceship.zsh
