brew "ag"
brew "asdf"
brew "bat"
brew "curl"
brew "delta"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "git"
brew "glow"
brew "go"
brew "k3d"
brew "k9s"
brew "kubectl"
brew "neovim"
brew "nnn"
brew "ripgrep"
brew "rsync"
brew "starship"
brew "tmux"
brew "yq"
brew "yt-dlp"
brew "zoxide"

unless ENV["HOMEBREW_TERMINAL"]
  tap "koekeishiya/formulae"

  brew "koekeishiya/formulae/skhd"
  brew "koekeishiya/formulae/yabai"

  cask "cursor"
  cask "docker"
  cask "font-ibm-plex"
  cask "font-jetbrains-mono"
  cask "google-chrome"
  cask "raycast"
  cask "spotify"
  cask "wezterm"
  cask "zen"
end
