brew "asdf"
brew "bat"
brew "coreutils"
brew "curl"
brew "delta"
brew "fd"
brew "ffmpeg"
brew "findutils"
brew "fish"
brew "fzf"
brew "gawk"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "grep"
brew "jq"
brew "k3d"
brew "k9s"
brew "kubectl"
brew "neovim"
brew "pgcli"
brew "ripgrep"
brew "rsync"
brew "starship"
brew "terraform"
brew "tmux"
brew "yq"
brew "yt-dlp"
brew "zoxide"

unless ENV["HOMEBREW_TERMINAL"]
  tap "koekeishiya/formulae"

  brew "koekeishiya/formulae/skhd"
  brew "koekeishiya/formulae/yabai"

  cask "cursor"
  cask "docker-desktop"
  cask "font-ibm-plex"
  cask "font-jetbrains-mono"
  cask "google-chrome"
  cask "raycast"
  cask "spotify"
  cask "wezterm"
  cask "zen"
end
