#!/usr/bin/env fish

function install_brew_packages -a terminal
    log "installing packages"
    if test -n "$terminal"
        env HOMEBREW_TERMINAL=1 brew bundle
    else
        brew bundle
    end
    or return $status
end

function terminal -d 'Provision terminal environment'
    log "provisioning terminal utilities for $USER"

    install_brew_packages --terminal
    or return $status

    log 'adding brew path to fish'
    fish_add_path /opt/homebrew/bin

    log 'setting m\'s default shell to fish'
    sudo chsh -s /opt/homebrew/bin/fish $USER

    read -P "Would you like to sync desktop configurations? [Y/n] " confirm
    switch $confirm
        case n N
            echo 'skipping desktop sync'
        case '*'
            log 'running sync script for desktop'
            ./sync --desktop
    end

    read -P "Would you like to sync git configurations? [Y/n] " confirm
    switch $confirm
        case n N
            echo 'skipping git sync'
        case '*'
            log 'running sync script for git'
            ./sync --git
    end

    echo 'done provisioning.'
end

function desktop -d 'Provision a macOS desktop environment'
    log "provisioning desktop environment for $USER"

    install_brew_packages
    or return $status

    test (uname) != Darwin
    and return 1

    read -P "Would you like to delete old login items? [y/N] " confirm
    switch $confirm
        case y Y
            log "deleting old login items"
            osascript -e 'tell application "System Events" to delete every login item'
    end

    log 'adding wezterm to login items'
    osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/WezTerm.app", hidden:false}'

    log 'adding raycast to login items'
    osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Raycast.app", hidden:false}'

    log 'installing yabai service'
    yabai --install-service
    defaults write com.apple.dock mru-spaces -bool false
    yabai --start-service

    log 'installing skhd service'
    skhd --install-service
    log 'configuring skhd to use bash shell for better performance'
    ./scripts/configure_skhd_for_performance.fish
    skhd --stop-service
    skhd --start-service

    log 'installing tmux package manager'
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

    echo "done provisioning."
end

function log -a message
    set_color blue
    echo -n "==> "
    set_color normal
    echo "$message"
end

$argv[1]
