#!/opt/homebrew/bin/zsh

# mxfng.sync | Run to sync dotfiles to $HOME and brew bundle.

BASEDIR="$(dirname "$(realpath -s "$0")")"
ERROUT=false; ERRC=0    # ERROR flag and counter
trap "ERROUT=true; ERRC=$((ERRC+1))" ERR

brewsync()  # Installs dependencies Homebrew and Git
{
    which -s brew
    if [[ $? != 0 ]] ; then
        echo Installing Homebrew
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/opt/homebrew/bin/brew shellenv)"
        brew install git
    fi
}

gitsync()   # Remote pull or remote clone
{
    if [ -d $LOCAL_REPO ] && [ ! -d .git ]; then
        cd $LOCAL_REPO
    fi

    if [ -d .git ]; then
        echo Pulling remote
        git pull
    else
        echo Cloning remote
        mkdir -p $LOCAL_REPO
        git clone https://github.com/mxfng/dotfiles $LOCAL_REPO
        cd $LOCAL_REPO
        if ! git remote -v | grep -q 'origin	git@github.com:mxfng/dotfiles (fetch)'$'\n''origin	git@github.com:mxfng/dotfiles (push)'; then
            echo "Setting remote git URL to git@github.com:mxfng/dotfiles"
            git remote set-url origin git@github.com:mxfng/dotfiles
        fi
    fi
}

zshsync()   # Swaps to brew zsh and adds iTerm2 Shell Integration
{
    if [[ $(which zsh) != "$(brew --prefix)/bin/zsh" ]]; then
        echo Current active Zsh will swap to $(which zsh)
        chsh -s $(which zsh)    # Set Default Shell to Homebrew Zsh
    fi

    if [[ "$OSTYPE" == "darwin"* ]]; then
        # iTerm2 Shell Integration for Zsh
        curl -L https://iterm2.com/shell_integration/zsh \
        -o $PWD/.config/iTerm2/.iterm2_shell_integration.zsh
        touch ~/.hushlogin          # Silence prompt at login
    fi
}

arm64cleanup()  # Addresses any M1-specific issues
{
    if [[ $(uname -m) == 'arm64' ]]; then
        echo Cleaning up M1 dependencies
        # Unused
    fi
}

# ----------------------------------------------------------------

echo Syncing mxfng.dotfiles.$OSTYPE

cd $BASEDIR; LOCAL_REPO=~/Developer/dotfiles

if [[ "$OSTYPE" == "darwin"* ]]; then brewsync; fi
gitsync     # Git remote pull or clone

if [[ "$OSTYPE" == "darwin"* ]]; then
    echo Running Brewfile
    brew update; brew bundle    # Run Brewfile
fi

zshsync         # Swap to Homebrew zsh; add iTerm 2

arm64cleanup    # Address any M1-specific issues

rm -f $PWD/Brewfile.lock.json   # Wipe Brewfile debugging output

# Rm .config files to swap in $HOME
for DOTFILE in ~/.zprofile ~/.zshrc ~/.gitconfig; do
    rm -f $DOTFILE
done

# Source .config files in $HOME
echo "source ${PWD}/.config/shell/profile" >> ~/.zprofile
echo "source ${PWD}/.config/zsh/.zshrc" >> ~/.zshrc

# Symlink .config files in $HOME
ln -s $PWD/.config/git/.gitconfig ~/.gitconfig

# ~/ Setup
mkdir -p ~/.cache/zsh ~/.cache/node ~/.nvm ~/Developer  ~/.local/bin/$USER

if $ERROUT; then
    echo -e "\e[1;31mThere were $ERRC or more errors during sync.\e[0m"
    echo -e '\e[1;31mPlease reference the output above for more information on the error(s).\e[0m'
    echo -e '\e[1;31mSyncing mxfng.dotfiles failed\e[0m'
else
    source ~/.zprofile; source ~/.zshrc
    echo "User-defined shell config files go in \`~/.local/bin/${USER}\`"
    echo 'Restart your iTerm2 shell to reflect preferences sync'
    echo -e '\e[1;32mSynced mxfng.dotfiles\e[0m'
fi