#!/usr/bin/env zsh

# mxfng.aliases | Separate file for alias commands.

# Sudo not required for some system commands
for command in shutdown poweroff reboot; do
	alias $command="sudo $command"
done
unset command

# Core Verbosity + Settings
alias \
	h='cd ~; clear' \
	sync="zsh ${BASEDIR}/sync" \
	sshx="zsh ${BASEDIR}/.config/ssh/sshx" \
	rm='rm -iv' \
	cp='cp -iv' \
	mv='mv -iv' \
	bc='bc -ql' \
	mkd="mkdir -pv" \
	rmd="rm -rf" \
	x86='arch -x86_64'

# Colorize Commands
alias \
	ls='ls --color=auto' \
	la='ls -a'

alias \
	e="$EDITOR" \
	cdev="$DEV" \
	cdot="cd ${BASEDIR}"

# Python Specific
alias \
	python='python3' \
	pip-user='PIP_REQUIRE_VIRTUALENV=false python3 -m pip'

# For Fun
alias \
	poop="echo 💩"
