#!/opt/homebrew/bin/zsh

# mxfng.aliasrc | Separate file for alias commands.

# Sudo not required for some system commands
for command in shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Core Verbosity + Settings
alias \
	rm='rm -iv' \
	cp='cp -iv' \
	mv='mv -iv' \
	bc='bc -ql' \
	mkd="mkdir -pv" \
	sync="sh ${BASEDIR}/sync.sh"

# Colorize Commands
alias \
	ls="gls --color=auto"

alias \
    e="$EDITOR"\
	cdev="cd ~/Developer"\
	cdot="cd ${BASEDIR}"

# Python Specific
alias pip-user='PIP_REQUIRE_VIRTUALENV=false python3 -m pip'