#!/opt/homebrew/bin/zsh

# mxfng.aliasrc | Separate file for alias commands.

# Sudo not required for some system commands
for command in shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Core Verbosity + Settings
alias \
	h='cd ~; clear' \
	sync="zsh ${BASEDIR}/sync" \
	rm='rm -iv' \
	cp='cp -iv' \
	mv='mv -iv' \
	bc='bc -ql' \
	mkd="mkdir -pv" \
	rmd="rm -rf"

# Colorize Commands
alias \
	ls='ls --color=auto' \
	la='ls -a'

alias \
    e="$EDITOR"\
	cdev="$DEV"\
	cdot="cd ${BASEDIR}"

# Python Specific
alias \
	python='python3' \
	pip-user='PIP_REQUIRE_VIRTUALENV=false python3 -m pip'

# Vim
alias \
	vim="vim -u ${CONFIG_HOME}/vim/.vimrc"

# For Fun
alias \
	poop="echo 💩"