#!/usr/bin/env zsh

# mxfng.profile | Runs on login. Environmental variables are set here.

# Locates dotfiles folder via the symlink path
export BASEDIR=$(echo "$(dirname "$(readlink "$0" || echo "$0")")" | rev | cut -d '/' -f3- | rev)

# ~/ Minimalism
export CONFIG_HOME=$BASEDIR/.config
export CACHE_HOME=$HOME/.cache
export ZDOTDIR=$CONFIG_HOME/zsh
export DEV=$BASEDIR/..

# Default Programs:
export EDITOR="code"

# Python
export PYTHONSTARTUP=$CONFIG_HOME/python/.pythonrc.py
export PIP_REQUIRE_VIRTUALENV=false

# Node
export NVM_DIR=~/.nvm
export NODE_REPL_HISTORY=~/.cache/node/history
