#!/opt/homebrew/bin/zsh

# mxfng.profile | Runs on login. Environmental variables are set here.

# Homebrew in PATH
eval "$(/opt/homebrew/bin/brew shellenv)"

# Ruby in PATH
eval "$(rbenv init -)"

# Python
export PIP_REQUIRE_VIRTUALENV=false

# Locates dotfiles folder via the symlink path
export BASEDIR=$(echo "$(dirname "$(realpath -s "$0")")" | rev | cut -d '/' -f3- | rev)

# Default Programs:
export EDITOR="code"
export NVM_DIR=~/.nvm

# ~/ Minimalism
export CONFIG_HOME=$BASEDIR/.config
export CACHE_HOME=$HOME/.cache
export ZDOTDIR=$CONFIG_HOME/zsh
export DEV=$BASEDIR/..