#!/usr/bin/env zsh

# mxfng.scripts | Separate file for shell scripts encapsulated in functions. This is mostly experimental.

# Sets the title of the Terminal tab to the text passed to it.

function title {
    echo -ne "\033]0;"$*"\007"
}

function gpt {
    open "https://chat.openai.com"
}